// <auto-generated />
using System;
using ExplorandoMarteComTecnologia_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExplorandoMarteComTecnologia_API.Migrations
{
    [DbContext(typeof(ExplorarMarteDBContext))]
    partial class ExplorarMarteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.AvaliacaoRespostasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bom")
                        .HasColumnType("int");

                    b.Property<int>("Excelente")
                        .HasColumnType("int");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pessimo")
                        .HasColumnType("int");

                    b.Property<int>("Regular")
                        .HasColumnType("int");

                    b.Property<int>("Ruim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvaliacaoRespostas");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.AvaliacaoSugestaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sugestao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AvaliacaoSugestao");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.IngressoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Ingresso");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.IngressoPasseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key_Ingresso")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("ObrasLidas")
                        .HasColumnType("bit");

                    b.Property<bool>("QuestionarioFeito")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("IngressoPasse");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.IngressoVendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Venda")
                        .HasColumnType("int");

                    b.Property<string>("Key_Ingresso")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("IngressoVenda");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.PasseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PassesAtivos")
                        .HasColumnType("int");

                    b.Property<int>("PassesObrasLidas")
                        .HasColumnType("int");

                    b.Property<int>("PassesQuestionarioFeito")
                        .HasColumnType("int");

                    b.Property<int>("PassesTotal")
                        .HasColumnType("int");

                    b.Property<int>("PassesUsados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Passe");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.QuestionarioRespostasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Acertos")
                        .HasColumnType("int");

                    b.Property<int>("Erros")
                        .HasColumnType("int");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionarioRespostas");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.RelatorioIngressosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("RelatorioData")
                        .HasColumnType("date");

                    b.Property<int>("TotalIngressosInteiro")
                        .HasColumnType("int");

                    b.Property<int>("TotalIngressosIsentos")
                        .HasColumnType("int");

                    b.Property<int>("TotalIngressosMeia")
                        .HasColumnType("int");

                    b.Property<int>("TotalIngressosVendidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RelatorioIngressos");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.RelatorioVendasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DinheiroTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadePagamentoCredito")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePagamentoDebito")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePagamentoPix")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RelatorioData")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("RelatorioVendas");
                });

            modelBuilder.Entity("ExplorandoMarteComTecnologia_API.Models.VendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
